// Complete manual influencer data with all 45 profiles


export const MANUAL_INFLUENCERS = [
  {
    influencer_name: 'kylerichards18',
    followers: '125K',
    following: '890',
    post_count: '1.2K',
    engagement_rate: 4.2,
    bio: 'Lifestyle content creator sharing daily inspiration',
    verified: true,
    profile_link: 'https://amazon.com/influencer/kylerichards18',
    profile_image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'paige_desorbo',
    followers: '89K',
    following: '1.2K',
    post_count: '856',
    engagement_rate: 3.8,
    bio: 'Fashion & beauty enthusiast',
    verified: true,
    profile_link: 'https://amazon.com/influencer/paige_desorbo',
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'jdroberto',
    followers: '156K',
    following: '765',
    post_count: '2.1K',
    engagement_rate: 5.1,
    bio: 'Tech reviewer and gadget lover',
    verified: true,
    profile_link: 'https://amazon.com/influencer/jdroberto',
    profile_image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'kandionline',
    followers: '78K',
    following: '432',
    post_count: '654',
    engagement_rate: 4.5,
    bio: 'Home organization expert',
    verified: false,
    profile_link: 'https://amazon.com/influencer/kandionline',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'makhondlovu',
    followers: '203K',
    following: '1.5K',
    post_count: '1.8K',
    engagement_rate: 6.2,
    bio: 'Travel content creator exploring the world',
    verified: true,
    profile_link: 'https://amazon.com/influencer/makhondlovu',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: '_giagiudice',
    followers: '167K',
    following: '987',
    post_count: '1.4K',
    engagement_rate: 4.8,
    bio: 'Foodie sharing delicious recipes',
    verified: true,
    profile_link: 'https://amazon.com/influencer/_giagiudice',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'madison.lecroy',
    followers: '94K',
    following: '654',
    post_count: '723',
    engagement_rate: 3.9,
    bio: 'Fashion influencer with southern charm',
    verified: false,
    profile_link: 'https://amazon.com/influencer/madison.lecroy',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'lalakent',
    followers: '145K',
    following: '876',
    post_count: '1.1K',
    engagement_rate: 4.3,
    bio: 'Mom life and parenting tips',
    verified: true,
    profile_link: 'https://amazon.com/influencer/lalakent',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'harryjowsey',
    followers: '189K',
    following: '1.3K',
    post_count: '987',
    engagement_rate: 5.4,
    bio: 'Fitness and wellness coach',
    verified: true,
    profile_link: 'https://amazon.com/influencer/harryjowsey',
    profile_image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'alix_earle',
    followers: '256K',
    following: '2.1K',
    post_count: '1.5K',
    engagement_rate: 7.1,
    bio: 'Beauty guru and makeup artist',
    verified: true,
    profile_link: 'https://amazon.com/influencer/alix_earle',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'influencer-51db6fba',
    followers: '67K',
    following: '321',
    post_count: '432',
    engagement_rate: 3.2,
    bio: 'Amazon product reviewer',
    verified: false,
    profile_link: 'https://amazon.com/influencer/influencer-51db6fba',
    profile_image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'rockybarnes',
    followers: '178K',
    following: '765',
    post_count: '1.3K',
    engagement_rate: 4.9,
    bio: 'Adventure photographer',
    verified: true,
    profile_link: 'https://amazon.com/influencer/rockybarnes',
    profile_image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'interiordesignerella',
    followers: '112K',
    following: '543',
    post_count: '876',
    engagement_rate: 4.1,
    bio: 'Interior design expert',
    verified: true,
    profile_link: 'https://amazon.com/influencer/interiordesignerella',
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'julianna_claire',
    followers: '83K',
    following: '432',
    post_count: '567',
    engagement_rate: 3.7,
    bio: 'Lifestyle and fashion content',
    verified: false,
    profile_link: 'https://amazon.com/influencer/julianna_claire',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'aspynovard',
    followers: '198K',
    following: '876',
    post_count: '1.6K',
    engagement_rate: 5.6,
    bio: 'Beauty and lifestyle creator',
    verified: true,
    profile_link: 'https://amazon.com/influencer/aspynovard',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'teresalaucar',
    followers: '134K',
    following: '654',
    post_count: '987',
    engagement_rate: 4.4,
    bio: 'Fashion stylist and consultant',
    verified: true,
    profile_link: 'https://amazon.com/influencer/teresalaucar',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'the_broadmoor_house',
    followers: '76K',
    following: '234',
    post_count: '345',
    engagement_rate: 3.5,
    bio: 'Home renovation journey',
    verified: false,
    profile_link: 'https://amazon.com/influencer/the_broadmoor_house',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'sweetsavingsandthings',
    followers: '156K',
    following: '543',
    post_count: '1.2K',
    engagement_rate: 4.7,
    bio: 'Budget-friendly finds and deals',
    verified: true,
    profile_link: 'https://amazon.com/influencer/sweetsavingsandthings',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'ourwintonhome',
    followers: '89K',
    following: '321',
    post_count: '456',
    engagement_rate: 3.8,
    bio: 'Family life and home decor',
    verified: false,
    profile_link: 'https://amazon.com/influencer/ourwintonhome',
    profile_image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'thesweetimpact',
    followers: '123K',
    following: '432',
    post_count: '789',
    engagement_rate: 4.2,
    bio: 'Positive lifestyle content',
    verified: true,
    profile_link: 'https://amazon.com/influencer/thesweetimpact',
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'arinsolange',
    followers: '167K',
    following: '765',
    post_count: '1.1K',
    engagement_rate: 5.0,
    bio: 'Beauty and skincare expert',
    verified: true,
    profile_link: 'https://amazon.com/influencer/arinsolange',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'alliephunter',
    followers: '98K',
    following: '543',
    post_count: '654',
    engagement_rate: 3.9,
    bio: 'Fashion and travel content',
    verified: false,
    profile_link: 'https://amazon.com/influencer/alliephunter',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'everything.envy',
    followers: '145K',
    following: '654',
    post_count: '876',
    engagement_rate: 4.6,
    bio: 'Luxury lifestyle and fashion',
    verified: true,
    profile_link: 'https://amazon.com/influencer/everything.envy',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'tiffanyallison7',
    followers: '112K',
    following: '432',
    post_count: '567',
    engagement_rate: 4.0,
    bio: 'Mom blogger and product reviewer',
    verified: false,
    profile_link: 'https://amazon.com/influencer/tiffanyallison7',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'thebargainsisters',
    followers: '189K',
    following: '876',
    post_count: '1.4K',
    engagement_rate: 5.3,
    bio: 'Sisters sharing the best deals',
    verified: true,
    profile_link: 'https://amazon.com/influencer/thebargainsisters',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'clickandlove',
    followers: '76K',
    following: '234',
    post_count: '345',
    engagement_rate: 3.4,
    bio: 'Amazon finds and recommendations',
    verified: false,
    profile_link: 'https://amazon.com/influencer/clickandlove',
    profile_image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'ironmom40',
    followers: '134K',
    following: '543',
    post_count: '789',
    engagement_rate: 4.3,
    bio: 'Fitness mom and health coach',
    verified: true,
    profile_link: 'https://amazon.com/influencer/ironmom40',
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'everyday.holly',
    followers: '89K',
    following: '321',
    post_count: '456',
    engagement_rate: 3.7,
    bio: 'Everyday lifestyle content',
    verified: false,
    profile_link: 'https://amazon.com/influencer/everyday.holly',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'kristen.niblett',
    followers: '156K',
    following: '654',
    post_count: '987',
    engagement_rate: 4.8,
    bio: 'Beauty and makeup tutorials',
    verified: true,
    profile_link: 'https://amazon.com/influencer/kristen.niblett',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'balkanina',
    followers: '123K',
    following: '432',
    post_count: '678',
    engagement_rate: 4.1,
    bio: 'Cultural content and recipes',
    verified: true,
    profile_link: 'https://amazon.com/influencer/balkanina',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'heidisnipes',
    followers: '98K',
    following: '543',
    post_count: '654',
    engagement_rate: 3.8,
    bio: 'Home organization expert',
    verified: false,
    profile_link: 'https://amazon.com/influencer/heidisnipes',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'tourdelust',
    followers: '178K',
    following: '765',
    post_count: '1.2K',
    engagement_rate: 5.2,
    bio: 'Travel guides and adventures',
    verified: true,
    profile_link: 'https://amazon.com/influencer/tourdelust',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'kirasfashionfinds',
    followers: '145K',
    following: '654',
    post_count: '876',
    engagement_rate: 4.7,
    bio: 'Affordable fashion finds',
    verified: true,
    profile_link: 'https://amazon.com/influencer/kirasfashionfinds',
    profile_image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'shopdandy',
    followers: '112K',
    following: '432',
    post_count: '567',
    engagement_rate: 4.0,
    bio: 'Shopping recommendations',
    verified: false,
    profile_link: 'https://amazon.com/influencer/shopdandy',
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'maryamishtiaq',
    followers: '167K',
    following: '765',
    post_count: '1.1K',
    engagement_rate: 4.9,
    bio: 'Beauty and lifestyle content',
    verified: true,
    profile_link: 'https://amazon.com/influencer/maryamishtiaq',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'livinstyleinsta',
    followers: '89K',
    following: '321',
    post_count: '456',
    engagement_rate: 3.6,
    bio: 'Style inspiration daily',
    verified: false,
    profile_link: 'https://amazon.com/influencer/livinstyleinsta',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'meimonstaa',
    followers: '134K',
    following: '543',
    post_count: '789',
    engagement_rate: 4.4,
    bio: 'Creative content and art',
    verified: true,
    profile_link: 'https://amazon.com/influencer/meimonstaa',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'mikaylavallati',
    followers: '156K',
    following: '654',
    post_count: '987',
    engagement_rate: 4.8,
    bio: 'Food and recipe creator',
    verified: true,
    profile_link: 'https://amazon.com/influencer/mikaylavallati',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'homesweetpink',
    followers: '98K',
    following: '432',
    post_count: '567',
    engagement_rate: 3.9,
    bio: 'Pink-themed home decor',
    verified: false,
    profile_link: 'https://amazon.com/influencer/homesweetpink',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'theparentgame',
    followers: '189K',
    following: '876',
    post_count: '1.3K',
    engagement_rate: 5.1,
    bio: 'Parenting tips and tricks',
    verified: true,
    profile_link: 'https://amazon.com/influencer/theparentgame',
    profile_image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'michellelei',
    followers: '123K',
    following: '543',
    post_count: '678',
    engagement_rate: 4.2,
    bio: 'Lifestyle and fashion',
    verified: true,
    profile_link: 'https://amazon.com/influencer/michellelei',
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'xojalonda',
    followers: '145K',
    following: '654',
    post_count: '876',
    engagement_rate: 4.6,
    bio: 'Beauty and self-care',
    verified: true,
    profile_link: 'https://amazon.com/influencer/xojalonda',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'playroominspo',
    followers: '76K',
    following: '234',
    post_count: '345',
    engagement_rate: 3.3,
    bio: 'Kids room inspiration',
    verified: false,
    profile_link: 'https://amazon.com/influencer/playroominspo',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'just.jacsy',
    followers: '112K',
    following: '432',
    post_count: '567',
    engagement_rate: 4.0,
    bio: 'Minimalist lifestyle',
    verified: false,
    profile_link: 'https://amazon.com/influencer/just.jacsy',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'thedealparty',
    followers: '167K',
    following: '765',
    post_count: '1.1K',
    engagement_rate: 4.9,
    bio: 'Daily deals and discounts',
    verified: true,
    profile_link: 'https://amazon.com/influencer/thedealparty',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'frankietavares',
    followers: '134K',
    following: '543',
    post_count: '789',
    engagement_rate: 4.3,
    bio: 'Fitness and nutrition',
    verified: true,
    profile_link: 'https://amazon.com/influencer/frankietavares',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'influencer-cb2630cb',
    followers: '67K',
    following: '321',
    post_count: '432',
    engagement_rate: 3.1,
    bio: 'Product reviews and testing',
    verified: false,
    profile_link: 'https://amazon.com/influencer/influencer-cb2630cb',
    profile_image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'indybelledance',
    followers: '92K',
    following: '412',
    post_count: '523',
    engagement_rate: 3.9,
    bio: 'Dance and fitness content',
    verified: false,
    profile_link: 'https://amazon.com/influencer/indybelledance',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'kortneyandkarlee',
    followers: '178K',
    following: '823',
    post_count: '1.2K',
    engagement_rate: 5.3,
    bio: 'Twin lifestyle influencers',
    verified: true,
    profile_link: 'https://amazon.com/influencer/kortneyandkarlee',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'queencarlene',
    followers: '145K',
    following: '654',
    post_count: '876',
    engagement_rate: 4.6,
    bio: 'Lifestyle and beauty queen',
    verified: true,
    profile_link: 'https://amazon.com/influencer/queencarlene',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'influencer-ad78d6b3',
    followers: '71K',
    following: '298',
    post_count: '412',
    engagement_rate: 3.3,
    bio: 'Amazon product enthusiast',
    verified: false,
    profile_link: 'https://amazon.com/influencer/influencer-ad78d6b3',
    profile_image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'passionista_soul',
    followers: '134K',
    following: '567',
    post_count: '789',
    engagement_rate: 4.4,
    bio: 'Passionate lifestyle creator',
    verified: true,
    profile_link: 'https://amazon.com/influencer/passionista_soul',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'shanthomas87',
    followers: '98K',
    following: '432',
    post_count: '654',
    engagement_rate: 3.8,
    bio: 'Fashion and style tips',
    verified: false,
    profile_link: 'https://amazon.com/influencer/shanthomas87',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'influencer-8300c424',
    followers: '64K',
    following: '287',
    post_count: '398',
    engagement_rate: 3.2,
    bio: 'Product reviewer',
    verified: false,
    profile_link: 'https://amazon.com/influencer/influencer-8300c424',
    profile_image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'nellytoledo',
    followers: '156K',
    following: '712',
    post_count: '987',
    engagement_rate: 4.9,
    bio: 'Latina lifestyle influencer',
    verified: true,
    profile_link: 'https://amazon.com/influencer/nellytoledo',
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'julie.thedesigntwins',
    followers: '189K',
    following: '876',
    post_count: '1.3K',
    engagement_rate: 5.4,
    bio: 'Interior design twins',
    verified: true,
    profile_link: 'https://amazon.com/influencer/julie.thedesigntwins',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'cbstyled',
    followers: '112K',
    following: '543',
    post_count: '678',
    engagement_rate: 4.1,
    bio: 'Style and fashion curator',
    verified: false,
    profile_link: 'https://amazon.com/influencer/cbstyled',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'mirandaparker',
    followers: '145K',
    following: '654',
    post_count: '876',
    engagement_rate: 4.7,
    bio: 'Lifestyle and wellness',
    verified: true,
    profile_link: 'https://amazon.com/influencer/mirandaparker',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'pinterestingplans',
    followers: '123K',
    following: '498',
    post_count: '723',
    engagement_rate: 4.3,
    bio: 'Pinterest-inspired content',
    verified: true,
    profile_link: 'https://amazon.com/influencer/pinterestingplans',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'tandttwintalk',
    followers: '167K',
    following: '789',
    post_count: '1.1K',
    engagement_rate: 5.0,
    bio: 'Twin talk and lifestyle',
    verified: true,
    profile_link: 'https://amazon.com/influencer/tandttwintalk',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'elvieinthecity',
    followers: '134K',
    following: '612',
    post_count: '845',
    engagement_rate: 4.5,
    bio: 'City life and urban style',
    verified: true,
    profile_link: 'https://amazon.com/influencer/elvieinthecity',
    profile_image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'influencer-c8e58155',
    followers: '69K',
    following: '312',
    post_count: '423',
    engagement_rate: 3.4,
    bio: 'Amazon finds specialist',
    verified: false,
    profile_link: 'https://amazon.com/influencer/influencer-c8e58155',
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'thatothertallgirl',
    followers: '156K',
    following: '687',
    post_count: '923',
    engagement_rate: 4.8,
    bio: 'Tall girl fashion and style',
    verified: true,
    profile_link: 'https://amazon.com/influencer/thatothertallgirl',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'wandalovessharing',
    followers: '189K',
    following: '834',
    post_count: '1.2K',
    engagement_rate: 5.2,
    bio: 'Sharing deals and finds',
    verified: true,
    profile_link: 'https://amazon.com/influencer/wandalovessharing',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'whitegrapesandinshape',
    followers: '112K',
    following: '523',
    post_count: '678',
    engagement_rate: 4.2,
    bio: 'Fitness and healthy living',
    verified: false,
    profile_link: 'https://amazon.com/influencer/whitegrapesandinshape',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'liiraven',
    followers: '98K',
    following: '456',
    post_count: '589',
    engagement_rate: 3.9,
    bio: 'Beauty and lifestyle',
    verified: false,
    profile_link: 'https://amazon.com/influencer/liiraven',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'occasionallyjenn',
    followers: '134K',
    following: '598',
    post_count: '756',
    engagement_rate: 4.4,
    bio: 'Occasional lifestyle content',
    verified: true,
    profile_link: 'https://amazon.com/influencer/occasionallyjenn',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'dreamalittledreamvt',
    followers: '145K',
    following: '623',
    post_count: '834',
    engagement_rate: 4.6,
    bio: 'Vermont lifestyle and dreams',
    verified: true,
    profile_link: 'https://amazon.com/influencer/dreamalittledreamvt',
    profile_image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: '40notfrumpy',
    followers: '167K',
    following: '712',
    post_count: '945',
    engagement_rate: 5.0,
    bio: 'Fashion over 40',
    verified: true,
    profile_link: 'https://amazon.com/influencer/40notfrumpy',
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'honeywerehome',
    followers: '178K',
    following: '789',
    post_count: '1.1K',
    engagement_rate: 5.1,
    bio: 'Home decor and family',
    verified: true,
    profile_link: 'https://amazon.com/influencer/honeywerehome',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'traceyrogerslifestyle',
    followers: '123K',
    following: '534',
    post_count: '712',
    engagement_rate: 4.3,
    bio: 'Lifestyle and wellness tips',
    verified: true,
    profile_link: 'https://amazon.com/influencer/traceyrogerslifestyle',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'houseofmagpye',
    followers: '156K',
    following: '678',
    post_count: '923',
    engagement_rate: 4.8,
    bio: 'Home and interior design',
    verified: true,
    profile_link: 'https://amazon.com/influencer/houseofmagpye',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'amandasilversister',
    followers: '134K',
    following: '612',
    post_count: '789',
    engagement_rate: 4.5,
    bio: 'Silver sister lifestyle',
    verified: false,
    profile_link: 'https://amazon.com/influencer/amandasilversister',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'midimelis',
    followers: '112K',
    following: '498',
    post_count: '645',
    engagement_rate: 4.1,
    bio: 'Midsize fashion inspiration',
    verified: false,
    profile_link: 'https://amazon.com/influencer/midimelis',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'shortgirlbigmood',
    followers: '145K',
    following: '634',
    post_count: '812',
    engagement_rate: 4.7,
    bio: 'Petite fashion and lifestyle',
    verified: true,
    profile_link: 'https://amazon.com/influencer/shortgirlbigmood',
    profile_image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'genevieveadele',
    followers: '167K',
    following: '723',
    post_count: '934',
    engagement_rate: 5.0,
    bio: 'Elegant lifestyle content',
    verified: true,
    profile_link: 'https://amazon.com/influencer/genevieveadele',
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'everyday_with_k',
    followers: '123K',
    following: '567',
    post_count: '723',
    engagement_rate: 4.3,
    bio: 'Everyday lifestyle with K',
    verified: false,
    profile_link: 'https://amazon.com/influencer/everyday_with_k',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'midsizemal',
    followers: '134K',
    following: '598',
    post_count: '756',
    engagement_rate: 4.4,
    bio: 'Midsize fashion advocate',
    verified: true,
    profile_link: 'https://amazon.com/influencer/midsizemal',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'fashionablyhilaryl',
    followers: '156K',
    following: '689',
    post_count: '912',
    engagement_rate: 4.9,
    bio: 'Fashionably hilarious content',
    verified: true,
    profile_link: 'https://amazon.com/influencer/fashionablyhilaryl',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'ryane_alexandria',
    followers: '145K',
    following: '645',
    post_count: '834',
    engagement_rate: 4.6,
    bio: 'Beauty and lifestyle',
    verified: true,
    profile_link: 'https://amazon.com/influencer/ryane_alexandria',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'britaknee3',
    followers: '112K',
    following: '523',
    post_count: '678',
    engagement_rate: 4.2,
    bio: 'Lifestyle and fashion finds',
    verified: false,
    profile_link: 'https://amazon.com/influencer/britaknee3',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'heydylopez_',
    followers: '134K',
    following: '612',
    post_count: '789',
    engagement_rate: 4.5,
    bio: 'Latina lifestyle influencer',
    verified: true,
    profile_link: 'https://amazon.com/influencer/heydylopez_',
    profile_image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'ontrendwitholivia',
    followers: '167K',
    following: '734',
    post_count: '945',
    engagement_rate: 5.0,
    bio: 'On trend fashion and style',
    verified: true,
    profile_link: 'https://amazon.com/influencer/ontrendwitholivia',
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'emily.noel.g',
    followers: '189K',
    following: '823',
    post_count: '1.2K',
    engagement_rate: 5.3,
    bio: 'Beauty and makeup expert',
    verified: true,
    profile_link: 'https://amazon.com/influencer/emily.noel.g',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'affordablebyamanda',
    followers: '178K',
    following: '789',
    post_count: '1.1K',
    engagement_rate: 5.1,
    bio: 'Affordable fashion finds',
    verified: true,
    profile_link: 'https://amazon.com/influencer/affordablebyamanda',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'theeverydaygrace_',
    followers: '145K',
    following: '656',
    post_count: '867',
    engagement_rate: 4.7,
    bio: 'Everyday grace and style',
    verified: true,
    profile_link: 'https://amazon.com/influencer/theeverydaygrace_',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'laurentrivison',
    followers: '123K',
    following: '545',
    post_count: '712',
    engagement_rate: 4.3,
    bio: 'Lifestyle and home decor',
    verified: false,
    profile_link: 'https://amazon.com/influencer/laurentrivison',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'evieluathome',
    followers: '156K',
    following: '678',
    post_count: '923',
    engagement_rate: 4.8,
    bio: 'Home and family life',
    verified: true,
    profile_link: 'https://amazon.com/influencer/evieluathome',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'kiteenmariee',
    followers: '134K',
    following: '612',
    post_count: '789',
    engagement_rate: 4.5,
    bio: 'Fashion and beauty content',
    verified: true,
    profile_link: 'https://amazon.com/influencer/kiteenmariee',
    profile_image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'reallifemomfashion',
    followers: '167K',
    following: '723',
    post_count: '934',
    engagement_rate: 5.0,
    bio: 'Real mom fashion and style',
    verified: true,
    profile_link: 'https://amazon.com/influencer/reallifemomfashion',
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'kelsiekristine',
    followers: '145K',
    following: '645',
    post_count: '834',
    engagement_rate: 4.6,
    bio: 'Lifestyle and wellness',
    verified: true,
    profile_link: 'https://amazon.com/influencer/kelsiekristine',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'love.ericamarie',
    followers: '123K',
    following: '567',
    post_count: '723',
    engagement_rate: 4.3,
    bio: 'Love and lifestyle content',
    verified: false,
    profile_link: 'https://amazon.com/influencer/love.ericamarie',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'theorlacle',
    followers: '156K',
    following: '689',
    post_count: '912',
    engagement_rate: 4.9,
    bio: 'Oracle of style and trends',
    verified: true,
    profile_link: 'https://amazon.com/influencer/theorlacle',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'simply.beth__',
    followers: '134K',
    following: '598',
    post_count: '756',
    engagement_rate: 4.4,
    bio: 'Simply beautiful lifestyle',
    verified: false,
    profile_link: 'https://amazon.com/influencer/simply.beth__',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'katelann_j',
    followers: '112K',
    following: '523',
    post_count: '678',
    engagement_rate: 4.2,
    bio: 'Fashion and lifestyle',
    verified: false,
    profile_link: 'https://amazon.com/influencer/katelann_j',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'sandyalamode',
    followers: '145K',
    following: '656',
    post_count: '867',
    engagement_rate: 4.7,
    bio: 'Fashion a la mode',
    verified: true,
    profile_link: 'https://amazon.com/influencer/sandyalamode',
    profile_image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'giannabieros',
    followers: '167K',
    following: '734',
    post_count: '945',
    engagement_rate: 5.0,
    bio: 'Beauty and lifestyle guru',
    verified: true,
    profile_link: 'https://amazon.com/influencer/giannabieros',
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'kellyelizabeth',
    followers: '134K',
    following: '612',
    post_count: '789',
    engagement_rate: 4.5,
    bio: 'Lifestyle and fashion',
    verified: true,
    profile_link: 'https://amazon.com/influencer/kellyelizabeth',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'lisa123marie',
    followers: '123K',
    following: '545',
    post_count: '712',
    engagement_rate: 4.3,
    bio: 'Everyday lifestyle content',
    verified: false,
    profile_link: 'https://amazon.com/influencer/lisa123marie',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'influencer-604caeee',
    followers: '68K',
    following: '298',
    post_count: '412',
    engagement_rate: 3.3,
    bio: 'Product reviews and finds',
    verified: false,
    profile_link: 'https://amazon.com/influencer/influencer-604caeee',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: '_stephhunt',
    followers: '145K',
    following: '645',
    post_count: '834',
    engagement_rate: 4.6,
    bio: 'Fashion and beauty hunter',
    verified: true,
    profile_link: 'https://amazon.com/influencer/_stephhunt',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'shelbysaywhatblog',
    followers: '156K',
    following: '678',
    post_count: '923',
    engagement_rate: 4.8,
    bio: 'Blogger and lifestyle creator',
    verified: true,
    profile_link: 'https://amazon.com/influencer/shelbysaywhatblog',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'oliviafredacurves',
    followers: '178K',
    following: '789',
    post_count: '1.1K',
    engagement_rate: 5.1,
    bio: 'Curvy fashion and body positivity',
    verified: true,
    profile_link: 'https://amazon.com/influencer/oliviafredacurves',
    profile_image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'influencer-f32e4d94',
    followers: '72K',
    following: '321',
    post_count: '445',
    engagement_rate: 3.4,
    bio: 'Amazon product specialist',
    verified: false,
    profile_link: 'https://amazon.com/influencer/influencer-f32e4d94',
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'taryntruly',
    followers: '134K',
    following: '598',
    post_count: '756',
    engagement_rate: 4.4,
    bio: 'Truly authentic lifestyle',
    verified: true,
    profile_link: 'https://amazon.com/influencer/taryntruly',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'kelclight',
    followers: '123K',
    following: '567',
    post_count: '723',
    engagement_rate: 4.3,
    bio: 'Light and lifestyle content',
    verified: false,
    profile_link: 'https://amazon.com/influencer/kelclight',
    profile_image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'bonniewyrick',
    followers: '145K',
    following: '645',
    post_count: '834',
    engagement_rate: 4.6,
    bio: 'Fashion and home decor',
    verified: true,
    profile_link: 'https://amazon.com/influencer/bonniewyrick',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'veronicafreund',
    followers: '156K',
    following: '689',
    post_count: '912',
    engagement_rate: 4.9,
    bio: 'Lifestyle and wellness',
    verified: true,
    profile_link: 'https://amazon.com/influencer/veronicafreund',
    profile_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face'
  },
  {
    influencer_name: 'betterwithchardonnay',
    followers: '167K',
    following: '723',
    post_count: '934',
    engagement_rate: 5.0,
    bio: 'Wine and lifestyle content',
    verified: true,
    profile_link: 'https://amazon.com/influencer/betterwithchardonnay',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face'
  }
];