export interface TaxOption {
  country: string;
  code: string;
  vat: number;
  gst: number;
  salesTax: number;
  misc: number;
  vatNote?: string;
  gstNote?: string;
  salesTaxNote?: string;
}

export const TAX_OPTIONS: TaxOption[] = [
  {
    country: "United States",
    code: "US",
    vat: 0,
    gst: 10,
    salesTax: 0,
    misc: 0,
    salesTaxNote: "Sales Tax is variable by state (e.g., California, New York).",
  },
  {
    country: "Canada",
    code: "CA",
    vat: 0,
    gst: 5,
    salesTax: 13,
    misc: 0,
    gstNote: "GST is variable by province (e.g., GST 5% or HST in certain regions like Ontario: 13%).",
  },
  {
    country: "Mexico",
    code: "MX",
    vat: 16,
    gst: 0,
    salesTax: 0,
    misc: 0,
    vatNote: "Standard VAT of 16%.",
  },
  {
    country: "Brazil",
    code: "BR",
    vat: 5,
    gst: 5,
    salesTax: 0,
    misc: 3,
    vatNote: "Brazil has complex tax structures including ICMS, IPI, PIS, and COFINS depending on the state.",
  },
  {
    country: "United Kingdom",
    code: "GB",
    vat: 20,
    gst: 0,
    salesTax: 0,
    misc: 0,
    vatNote: "Standard VAT of 20%.",
  },
  {
    country: "Germany",
    code: "DE",
    vat: 19,
    gst: 0,
    salesTax: 0,
    misc: 0,
    vatNote: "Standard VAT of 19%.",
  },
  {
    country: "Sweden",
    code: "SE",
    vat: 25,
    gst: 0,
    salesTax: 0,
    misc: 0,
    vatNote: "Standard VAT of 25%.",
  },
  {
    country: "Poland",
    code: "PL",
    vat: 23,
    gst: 0,
    salesTax: 0,
    misc: 0,
    vatNote: "Standard VAT of 23%.",
  },
  {
    country: "Turkey",
    code: "TR",
    vat: 18,
    gst: 0,
    salesTax: 0,
    misc: 0,
    vatNote: "Standard VAT of 18%.",
  },
  {
    country: "UAE",
    code: "AE",
    vat: 5,
    gst: 0,
    salesTax: 0,
    misc: 0,
    vatNote: "Standard VAT of 5%.",
  },
  {
    country: "India",
    code: "IN",
    vat: 0,
    gst: 18,
    salesTax: 0,
    misc: 0,
    gstNote: "GST rates vary from 5% to 28%, depending on the product category.",
  },
  {
    country: "France",
    code: "FR",
    vat: 20,
    gst: 0,
    salesTax: 0,
    misc: 0,
    vatNote: "Standard VAT of 20%.",
  },
  {
    country: "Italy",
    code: "IT",
    vat: 22,
    gst: 0,
    salesTax: 0,
    misc: 0,
    vatNote: "Standard VAT of 22%.",
  },
  {
    country: "Spain",
    code: "ES",
    vat: 21,
    gst: 0,
    salesTax: 0,
    misc: 0,
    vatNote: "Standard VAT of 21%.",
  },
  {
    country: "Netherlands",
    code: "NL",
    vat: 21,
    gst: 0,
    salesTax: 0,
    misc: 0,
    vatNote: "Standard VAT of 21%.",
  },
  {
    country: "Saudi Arabia",
    code: "SA",
    vat: 15,
    gst: 0,
    salesTax: 0,
    misc: 0,
    vatNote: "Standard VAT of 15%.",
  },
  {
    country: "Japan",
    code: "JP",
    vat: 0,
    gst: 0,
    salesTax: 10,
    misc: 0,
    salesTaxNote: "Standard Consumption Tax of 10%.",
  },
  {
    country: "Singapore",
    code: "SG",
    vat: 0,
    gst: 8,
    salesTax: 0,
    misc: 0,
    gstNote: "Standard GST of 8%.",
  },
  {
    country: "Australia",
    code: "AU",
    vat: 0,
    gst: 10,
    salesTax: 0,
    misc: 0,
    gstNote: "Standard GST of 10%.",
  },
];
